### ISSUE TITLE
语言回复报错speaker_id is required

### ISSUE THREAD

**Issue by DMB-codegang** [initialencounter/mykoishi#58]
使用文字和图片回复正常，测试了say指令正常，但是使用语音回复就会报错speaker_id is required
![image](https://github.com/user-attachments/assets/cc7597ed-700d-4a83-9fd6-1e8a536aff91)

**Comment by initialencounter** [comment]
感谢反馈，我现在来修复它

**Comment by initialencounter** [comment]
你用的是什么插件提供的vits服务？

**Comment by DMB-codegang** [comment]
使用的是open-vits

**Comment by initialencounter** [comment]
更新 open-vits 插件到 2.0.6 即可修复

**Comment by DMB-codegang** [comment]
遗憾的是，2.0.6貌似未能修复该问题
![image](https://github.com/user-attachments/assets/bf0f25bd-af59-44cf-b592-6710c35e5041)
![image](https://github.com/user-attachments/assets/e3c57a9e-67b1-4c56-a0ff-7ed6bf5e3242)

**Comment by initialencounter** [comment]
![image](https://github.com/user-attachments/assets/4d309094-a7fb-4929-a555-3eb0db8482ef)
![image](https://github.com/user-attachments/assets/70da14e5-34a2-45fd-9150-4778ce288104)

**Comment by initialencounter** [comment]
可是我这里没问题啊，要不重启一下koishi？

**Comment by initialencounter** [comment]
```yaml
davinci-003:ldu3y5:
  key:
    - sk-***
  baseURL: https://api.chatanywhere.com.cn
  output: voice
open-vits:hw05xm:
  defaultEngine: BERT-VITS2
  endpoint: http://127.0.0.1:23456
   ```
